#ifndef __PATCHER9X_VERSION_H__INCLUDED__

#define PATCHER9X_STR_(x) #x
#define PATCHER9X_STR(x) PATCHER9X_STR_(x)

#define PATCHER9X_MAJOR 0
#define PATCHER9X_MINOR 9

#ifndef PATCHER9X_PATCH
#define PATCHER9X_PATCH 86
#endif

/*#define PATCHER9X_TAG "RC1"*/

#ifdef PATCHER9X_TAG
# define PATCHER9X_VERSION_STR_BUILD(_ma, _mi, _pa, _tag) \
	_ma "." _mi "." _pa "-" _tag

# define PATCHER9X_VERSION_STR PATCHER9X_VERSION_STR_BUILD( \
	PATCHER9X_STR(PATCHER9X_MAJOR), \
	PATCHER9X_STR(PATCHER9X_MINOR), \
	PATCHER9X_STR(PATCHER9X_PATCH), \
	PATCHER9X_TAG)

#else
# define PATCHER9X_VERSION_STR_BUILD(_ma, _mi, _pa) \
	_ma "." _mi "." _pa

# define PATCHER9X_VERSION_STR PATCHER9X_VERSION_STR_BUILD( \
	PATCHER9X_STR(PATCHER9X_MAJOR), \
	PATCHER9X_STR(PATCHER9X_MINOR), \
	PATCHER9X_STR(PATCHER9X_PATCH))

#endif /* !PATCHER9X_TAG */

#define PATCHER9X_VERSION_NUM \
 	PATCHER9X_MAJOR,PATCHER9X_MINOR,PATCHER9X_PATCH,0 \

#endif /* __PATCHER9X_VERSION_H__INCLUDED__ */
