/****** Generated by vmm/makediff.c ******/
/****** for regenaration run make fasmdiff ******/

#ifndef __VMM_SPEEDNDIS_V4_DIFF_H__INCLUDED__
#define __VMM_SPEEDNDIS_V4_DIFF_H__INCLUDED__

/* bitmap of differences between file assembled by FASM and original file by Microsoft */
const uint8_t vmm_speedndis_v4_diff[] = {
	
	0x80, 0xC0, 0x00, 0xC0, 0x00, 0x00, 0x60, 0x66, 0x00, 0x06, 0x00, 0x18, 0x20, 0x00, 0x00, 
};

#endif /* __VMM_SPEEDNDIS_V4_DIFF_H__INCLUDED__ */
