/****** Generated by vmm/makediff.c ******/
/****** for regenaration run make fasmdiff ******/

#ifndef __VMM_SPEED_V7_DIFF_H__INCLUDED__
#define __VMM_SPEED_V7_DIFF_H__INCLUDED__

/* bitmap of differences between file assembled by FASM and original file by Microsoft */
const uint8_t vmm_speed_v7_diff[] = {
	
	0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 
};

#endif /* __VMM_SPEED_V7_DIFF_H__INCLUDED__ */
