/****** Generated by vmm/makediff.c ******/
/****** for regenaration run make fasmdiff ******/

#ifndef __VMM_SPEEDNDIS_V3_DIFF_H__INCLUDED__
#define __VMM_SPEEDNDIS_V3_DIFF_H__INCLUDED__

/* bitmap of differences between file assembled by FASM and original file by Microsoft */
const uint8_t vmm_speedndis_v3_diff[] = {
	
	0x80, 0xC0, 0x01, 0x80, 0x00, 0x00, 0xC0, 0xCC, 0x00, 0x0C, 0x00, 0x30, 0x40, 0x00, 
};

#endif /* __VMM_SPEEDNDIS_V3_DIFF_H__INCLUDED__ */
