/******************************************************************************
 * Copyright (c) 2022 Jaroslav Hensl                                          *
 *                                                                            *
 * Permission is hereby granted, free of charge, to any person                *
 * obtaining a copy of this software and associated documentation             *
 * files (the "Software"), to deal in the Software without                    *
 * restriction, including without limitation the rights to use,               *
 * copy, modify, merge, publish, distribute, sublicense, and/or sell          *
 * copies of the Software, and to permit persons to whom the                  *
 * Software is furnished to do so, subject to the following                   *
 * conditions:                                                                *
 *                                                                            *
 * The above copyright notice and this permission notice shall be             *
 * included in all copies or substantial portions of the Software.            *
 *                                                                            *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,            *
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES            *
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND                   *
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT                *
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,               *
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING               *
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR              *
 * OTHER DEALINGS IN THE SOFTWARE.                                            *
 *                                                                            *
*******************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <bitstream.h>
#include <bpatcher.h>

const char *h_header = \
	"/****** Generated by " __FILE__ " ******/\n" \
	"/****** for regenaration run make vmm/fasmdiff.h ******/\n\n" \
	"#ifndef __VMM_FASMDIFF_H__INCLUDED__\n" \
	"#define __VMM_FASMDIFF_H__INCLUDED__\n\n";

const char *h_footer = "#endif /* __VMM_FASMDIFF_H__INCLUDED__ */\n";

static size_t file_size(FILE *fp)
{
	size_t cur, end;
	
	cur = ftell(fp);
	fseek(fp, 0, SEEK_END);
	end = ftell(fp);
	fseek(fp, cur, SEEK_SET);
	
	return end;
}

int main(int argc, char *argv[])
{
	uint8_t *mem1 = NULL, *mem2 = NULL, *mem3 = NULL; /* buffer for fread */
	FILE *fp = NULL;
	size_t dumped_s, original_s, i, j;
	int status = EXIT_FAILURE;
	bitstream_t bs;

	fp = fopen("vmm/dump.bin", "rb");
	if(fp)
	{
		dumped_s = file_size(fp);
		mem1 = malloc(dumped_s);
		mem2 = malloc(dumped_s);
		mem3 = bs_mem_alloc(&bs, bs_calc_size(dumped_s));
		
		if(mem1 != NULL && mem2 != NULL)
		{
			fread(mem1, 1, dumped_s, fp);
			fclose(fp);
			fp = fopen("vmm/original.bin", "rb");
			if(fp)
			{
				original_s = file_size(fp);
				if(original_s == dumped_s)
				{
					uint8_t buf8 = 0;
					
					fread(mem2, 1, original_s, fp);
					diff_sieve(mem1, mem2, original_s, &bs);
					bs_reset(&bs);
					
					printf("%s", h_header);

					printf("/* bitmap of differences between file assembled by FASM and original file by Microsoft */\nconst uint8_t vmm_fasmdiff[] = {\n\t");
					for(i = 0, j = 0; i < original_s; i += 8, j++)
					{
						buf8 = bs_read_bit(&bs, 8);
						
						if(j % 16 == 0)
						{
							printf("\n\t");
						}
						printf("0x%02X, ", buf8);
					}
					printf("\n};\n\n");
					
					printf("%s", h_footer);
					
					status = EXIT_SUCCESS;
				}
				else
				{
					fprintf(stderr, "Error: file sizes of dump.bin and original.bin are not same\n");
				}
			}
			else
			{
				fprintf(stderr, "Error: file vmm/original.bin not found\n");
			}
		}
		else
		{
			fprintf(stderr, "Error: out of memory\n");
		}
	}
	else
	{
		fprintf(stderr, "Error: file vmm/dump.bin not found\n");
	}
	
	if(fp)
	{
		fclose(fp);
	}
	
	if(mem1) free(mem1);
	if(mem2) free(mem2);
	if(mem3) bs_mem_free(&bs);
	
	return status;
}
